# Generated by Django 6.0.1 on 2026-01-12 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.PositiveSmallIntegerField(help_text='NFL season year (e.g. 2025)')),
                ('week', models.PositiveSmallIntegerField(help_text='Week number within the season')),
                ('game_date', models.DateTimeField(help_text='Scheduled kickoff date and time')),
                ('venue', models.CharField(blank=True, max_length=200, null=True)),
                ('is_played', models.BooleanField(default=False)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='away_games', to='core.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_games', to='core.team')),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
                'ordering': ['season', 'week', 'game_date'],
                'constraints': [models.UniqueConstraint(fields=('season', 'week', 'home_team', 'away_team'), name='unique_game_per_week')],
            },
        ),
    ]
