import os
import psycopg2

# ----------------------------
# CONFIG
# ----------------------------
DB_CONFIG = {
    "host": "10.0.0.4",
    "port": 5432,
    "dbname": "nfl_analytics_2025",
    "user": "nfl_user",
    "password": "nfl_user",
}

SCHEMA_NAME = "analytics"
OUTPUT_DIR = "sql/views"
AUTHOR = "Arvind Thyagarajan"

# ----------------------------
# SCRIPT
# ----------------------------

def main():
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    conn = psycopg2.connect(**DB_CONFIG)
    cur = conn.cursor()

    # Fetch views using pg_class / pg_namespace (robust method)
    cur.execute(
        """
        SELECT
            c.relname AS view_name,
            pg_get_viewdef(c.oid, true) AS view_definition
        FROM pg_class c
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE c.relkind = 'v'
          AND n.nspname = %s
        ORDER BY c.relname;
        """,
        (SCHEMA_NAME,)
    )

    views = cur.fetchall()

    if not views:
        print(f"No views found in schema '{SCHEMA_NAME}'.")
        return

    print(f"Found {len(views)} views in schema '{SCHEMA_NAME}'.")

    for idx, row in enumerate(views, start=1):
        view_name = row[0]
        view_def = row[1]

        file_name = f"{idx:02d}_{view_name}.sql"
        file_path = os.path.join(OUTPUT_DIR, file_name)

        with open(file_path, "w") as f:
            f.write(f"""-- =====================================================
-- View: {SCHEMA_NAME}.{view_name}
-- Purpose: Auto-exported PostgreSQL view
-- Author: {AUTHOR}
-- Generated by: scripts/export_views.py
-- =====================================================

CREATE OR REPLACE VIEW {SCHEMA_NAME}.{view_name} AS
{view_def.strip()};
""")

        print(f"✔ Exported {view_name} → {file_path}")

    cur.close()
    conn.close()

    print("All views exported successfully.")


if __name__ == "__main__":
    main()

