-- =====================================================
-- View: analytics.player_game_facts
-- Purpose: Auto-exported PostgreSQL view
-- Author: Arvind Thyagarajan
-- Generated by: scripts/export_views.py
-- =====================================================

CREATE OR REPLACE VIEW analytics.player_game_facts AS
SELECT p.player_id,
    p.player_name,
    p.player_display_name,
    p."position",
    p.recent_team AS team,
    p.season,
    p.week,
    g.game_id,
    g.gameday,
    g.home_team,
    g.away_team,
        CASE
            WHEN p.recent_team = g.home_team THEN 'HOME'::text
            WHEN p.recent_team = g.away_team THEN 'AWAY'::text
            ELSE NULL::text
        END AS home_away,
    COALESCE(p.attempts, 0::bigint) AS passing_attempts,
    COALESCE(p.completions, 0::bigint) AS passing_completions,
    COALESCE(p.passing_yards, 0::bigint) AS passing_yards,
    COALESCE(p.passing_tds, 0::bigint) AS passing_tds,
    COALESCE(p.interceptions, 0::bigint) AS interceptions,
    COALESCE(p.sacks, 0::bigint) AS sacks,
    COALESCE(p.carries, 0::bigint) AS rushing_attempts,
    COALESCE(p.rushing_yards, 0::bigint) AS rushing_yards,
    COALESCE(p.rushing_tds, 0::bigint) AS rushing_tds,
    COALESCE(p.targets, 0::bigint) AS targets,
    COALESCE(p.receptions, 0::bigint) AS receptions,
    COALESCE(p.receiving_yards, 0::bigint) AS receiving_yards,
    COALESCE(p.receiving_tds, 0::bigint) AS receiving_tds,
    p.fantasy_points,
    p.fantasy_points_ppr
   FROM raw.nflverse_player_game_stats p
     LEFT JOIN raw.nflverse_games g ON p.season = g.season AND p.week = g.week AND (p.recent_team = g.home_team OR p.recent_team = g.away_team)
  WHERE p.season >= 2018
    AND p.season <= 2025
    AND (p."position" = ANY (ARRAY['QB'::text, 'RB'::text, 'WR'::text, 'TE'::text]))
    AND (
      p.season < 2025
      OR p.season_type = 'REG'
    );;
