-- =====================================================
-- View: analytics.player_game_facts_ppr
-- Purpose: Auto-exported PostgreSQL view
-- Author: Arvind Thyagarajan
-- Generated by: scripts/export_views.py
-- =====================================================

CREATE OR REPLACE VIEW analytics.player_game_facts_ppr AS
SELECT player_id,
    player_name,
    player_display_name,
    "position",
    team,
    season,
    week,
    game_id,
    gameday,
    home_team,
    away_team,
    home_away,
    passing_attempts,
    passing_completions,
    passing_yards,
    passing_tds,
    interceptions,
    sacks,
    rushing_attempts,
    rushing_yards,
    rushing_tds,
    targets,
    receptions,
    receiving_yards,
    receiving_tds,
    fantasy_points,
    fantasy_points_ppr,
    round(
        CASE
            WHEN season = 2025 THEN
                CASE
                    WHEN position = 'QB' THEN
                        passing_yards::numeric / 25.0
                        + (passing_tds * 4)::numeric
                        - (interceptions * 2)::numeric
                        + rushing_yards::numeric / 10.0
                        + (rushing_tds * 6)::numeric
                        + (COALESCE(passing_2pt_conversions, 0) * 2)::numeric
                        + (COALESCE(rushing_2pt_conversions, 0) * 2)::numeric
                        - (COALESCE(rushing_fumbles, 0) * 2)::numeric
                    WHEN position = 'RB' THEN
                        rushing_yards::numeric / 10.0
                        + (rushing_tds * 6)::numeric
                        + (receptions * 1)::numeric
                        + receiving_yards::numeric / 10.0
                        + (receiving_tds * 6)::numeric
                        + (COALESCE(rushing_2pt_conversions, 0) * 2)::numeric
                        + (COALESCE(receiving_2pt_conversions, 0) * 2)::numeric
                        - (COALESCE(rushing_fumbles, 0) * 2)::numeric
                        - (COALESCE(receiving_fumbles, 0) * 2)::numeric
                    WHEN position IN ('WR', 'TE') THEN
                        (receptions * 1)::numeric
                        + receiving_yards::numeric / 10.0
                        + (receiving_tds * 6)::numeric
                        + (COALESCE(receiving_2pt_conversions, 0) * 2)::numeric
                        - (COALESCE(receiving_fumbles, 0) * 2)::numeric
                    ELSE
                        passing_yards::numeric / 25.0
                        + (passing_tds * 4)::numeric
                        - (interceptions * 2)::numeric
                        + rushing_yards::numeric / 10.0
                        + (rushing_tds * 6)::numeric
                        + (receptions * 1)::numeric
                        + receiving_yards::numeric / 10.0
                        + (receiving_tds * 6)::numeric
                        + (COALESCE(passing_2pt_conversions, 0) * 2)::numeric
                        + (COALESCE(rushing_2pt_conversions, 0) * 2)::numeric
                        + (COALESCE(receiving_2pt_conversions, 0) * 2)::numeric
                        - (COALESCE(rushing_fumbles, 0) * 2)::numeric
                        - (COALESCE(receiving_fumbles, 0) * 2)::numeric
                END
            ELSE
                passing_yards::numeric / 25.0
                + (passing_tds * 4)::numeric
                - (interceptions * 2)::numeric
                + rushing_yards::numeric / 10.0
                + (rushing_tds * 6)::numeric
                + (receptions * 1)::numeric
                + receiving_yards::numeric / 10.0
                + (receiving_tds * 6)::numeric
                + (COALESCE(passing_2pt_conversions, 0) * 2)::numeric
                + (COALESCE(rushing_2pt_conversions, 0) * 2)::numeric
                + (COALESCE(receiving_2pt_conversions, 0) * 2)::numeric
                - (COALESCE(rushing_fumbles, 0) * 2)::numeric
                - (COALESCE(receiving_fumbles, 0) * 2)::numeric
        END,
        2
    ) AS ppr_points_calculated
   FROM analytics.player_game_facts f;;
