-- =====================================================
-- View: analytics.player_game_facts_ppr
-- Purpose: Auto-exported PostgreSQL view
-- Author: Arvind Thyagarajan
-- Generated by: scripts/export_views.py
-- =====================================================

CREATE OR REPLACE VIEW analytics.player_game_facts_ppr AS
SELECT player_id,
    player_name,
    player_display_name,
    "position",
    team,
    season,
    week,
    game_id,
    gameday,
    home_team,
    away_team,
    home_away,
    passing_attempts,
    passing_completions,
    passing_yards,
    passing_tds,
    interceptions,
    sacks,
    rushing_attempts,
    rushing_yards,
    rushing_tds,
    targets,
    receptions,
    receiving_yards,
    receiving_tds,
    fantasy_points,
    fantasy_points_ppr,
    round(passing_yards::numeric / 25.0 + (passing_tds * 4)::numeric - (interceptions * 2)::numeric + rushing_yards::numeric / 10.0 + (rushing_tds * 6)::numeric + (receptions * 1)::numeric + receiving_yards::numeric / 10.0 + (receiving_tds * 6)::numeric, 2) AS ppr_points_calculated
   FROM analytics.player_game_facts f;;
