-- =====================================================
-- View: analytics.player_game_features_usage
-- Purpose: Auto-exported PostgreSQL view
-- Author: Arvind Thyagarajan
-- Generated by: scripts/export_views.py
-- =====================================================

CREATE OR REPLACE VIEW analytics.player_game_features_usage AS
SELECT player_id,
    player_name,
    player_display_name,
    "position",
    team,
    season,
    week,
    game_id,
    gameday,
    home_team,
    away_team,
    home_away,
    passing_attempts,
    passing_completions,
    passing_yards,
    passing_tds,
    interceptions,
    sacks,
    rushing_attempts,
    rushing_yards,
    rushing_tds,
    targets,
    receptions,
    receiving_yards,
    receiving_tds,
    fantasy_points,
    fantasy_points_ppr,
    ppr_points_calculated,
    avg(targets) OVER (PARTITION BY player_id ORDER BY season, week ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS targets_last_3,
    avg(rushing_attempts) OVER (PARTITION BY player_id ORDER BY season, week ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS carries_last_3,
    avg(passing_attempts + rushing_attempts) OVER (PARTITION BY player_id ORDER BY season, week ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS touches_last_3
   FROM analytics.player_game_facts_ppr f;;
