-- =====================================================
-- View: analytics.player_game_features_v2
-- Purpose: Auto-exported PostgreSQL view
-- Author: Arvind Thyagarajan
-- Generated by: scripts/export_views.py
-- =====================================================

CREATE OR REPLACE VIEW analytics.player_game_features_v2 AS
SELECT player_id,
    player_name,
    "position",
    team,
    season,
    week,
    ppr_points_calculated,
    avg(ppr_points_calculated) OVER (PARTITION BY player_id ORDER BY season, week ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS ppr_avg_last_3,
    avg(ppr_points_calculated) OVER (PARTITION BY player_id ORDER BY season, week ROWS BETWEEN 4 PRECEDING AND CURRENT ROW) AS ppr_avg_last_5,
    avg(ppr_points_calculated) OVER (PARTITION BY player_id, season ORDER BY week ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS ppr_avg_season,
    avg(targets) OVER (PARTITION BY player_id ORDER BY season, week ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS targets_last_3,
    avg(rushing_attempts) OVER (PARTITION BY player_id ORDER BY season, week ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS carries_last_3,
    avg(passing_attempts + rushing_attempts) OVER (PARTITION BY player_id ORDER BY season, week ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS touches_last_3
   FROM analytics.player_game_facts_ppr f;;
