-- =====================================================
-- View: analytics.player_week_backtest
-- Purpose: Auto-exported PostgreSQL view
-- Author: Arvind Thyagarajan
-- Generated by: scripts/export_views.py
-- =====================================================

CREATE OR REPLACE VIEW analytics.player_week_backtest AS
SELECT f.player_id,
    f.player_name,
    f."position",
    f.team,
    f.season,
    f.forecast_week AS week,
    f.forecast_ppr_points,
    a.ppr_points_calculated AS actual_ppr_points,
    a.ppr_points_calculated - f.forecast_ppr_points AS error,
    abs(a.ppr_points_calculated - f.forecast_ppr_points) AS abs_error
   FROM analytics.player_week_forecast f
     JOIN analytics.player_game_facts_ppr a ON f.player_id = a.player_id AND f.season = a.season AND f.forecast_week = a.week;;
