-- =====================================================
-- View: analytics.player_week_forecast
-- Purpose: Auto-exported PostgreSQL view
-- Author: Arvind Thyagarajan
-- Generated by: scripts/export_views.py
-- =====================================================

CREATE OR REPLACE VIEW analytics.player_week_forecast AS
SELECT player_id,
    player_name,
    "position",
    team,
    season,
    week AS forecast_week,
    round(0.5 * ppr_avg_last_3 + 0.3 * ppr_avg_last_5 + 0.2 * ppr_avg_season, 2) AS forecast_ppr_points
   FROM analytics.player_game_features
  WHERE ppr_avg_last_3 IS NOT NULL AND ppr_avg_last_5 IS NOT NULL;;
