-- =====================================================
-- View: analytics.player_week_forecast_2024
-- Purpose: Auto-exported PostgreSQL view
-- Author: Arvind Thyagarajan
-- Generated by: scripts/export_views.py
-- =====================================================

CREATE OR REPLACE VIEW analytics.player_week_forecast_2024 AS
WITH last_2023 AS (
         SELECT DISTINCT ON (player_game_features_train.player_id) player_game_features_train.player_id,
            player_game_features_train.player_name,
            player_game_features_train."position",
            player_game_features_train.team,
            player_game_features_train.ppr_avg_last_3,
            player_game_features_train.ppr_avg_last_5,
            player_game_features_train.ppr_avg_season
           FROM analytics.player_game_features_train
          WHERE player_game_features_train.season = 2023
          ORDER BY player_game_features_train.player_id, player_game_features_train.week DESC
        )
 SELECT player_id,
    player_name,
    "position",
    team,
    2024 AS season,
    1 AS forecast_week,
    round(0.5 * ppr_avg_last_3 + 0.3 * ppr_avg_last_5 + 0.2 * ppr_avg_season, 2) AS forecast_ppr_points
   FROM last_2023
  WHERE ppr_avg_last_3 IS NOT NULL AND ppr_avg_last_5 IS NOT NULL;;
