-- =====================================================
-- View: analytics.player_week_forecast_enhanced
-- Purpose: Auto-exported PostgreSQL view
-- Author: Arvind Thyagarajan
-- Generated by: scripts/export_views.py
-- =====================================================

CREATE OR REPLACE VIEW analytics.player_week_forecast_enhanced AS
SELECT player_id,
    player_name,
    "position",
    team,
    season,
    week + 1 AS forecast_week,
    round(
        CASE "position"
            WHEN 'QB'::text THEN 0.6 * ppr_avg_last_3 + 0.3 * ppr_avg_last_5 + 0.1 * ppr_avg_season
            WHEN 'RB'::text THEN 0.4 * ppr_avg_last_3 + 0.4 * ppr_avg_last_5 + 0.2 * ppr_avg_season + 0.2 * COALESCE(carries_last_3, 0::numeric)
            WHEN 'WR'::text THEN 0.3 * ppr_avg_last_3 + 0.4 * ppr_avg_last_5 + 0.3 * ppr_avg_season + 0.3 * COALESCE(targets_last_3, 0::numeric)
            WHEN 'TE'::text THEN 0.2 * ppr_avg_last_3 + 0.4 * ppr_avg_last_5 + 0.4 * ppr_avg_season + 0.15 * COALESCE(targets_last_3, 0::numeric)
            ELSE NULL::numeric
        END, 2) AS forecast_ppr_points
   FROM analytics.player_game_features_v2
  WHERE ppr_avg_last_3 IS NOT NULL;;
