-- =====================================================
-- View: analytics.player_week_forecast_weighted
-- Purpose: Auto-exported PostgreSQL view
-- Author: Arvind Thyagarajan
-- Generated by: scripts/export_views.py
-- =====================================================

CREATE OR REPLACE VIEW analytics.player_week_forecast_weighted AS
SELECT player_id,
    player_name,
    "position",
    team,
    season,
    week + 1 AS forecast_week,
    round(
        CASE "position"
            WHEN 'QB'::text THEN 0.6 * ppr_avg_last_3 + 0.3 * ppr_avg_last_5 + 0.1 * ppr_avg_season
            WHEN 'RB'::text THEN 0.4 * ppr_avg_last_3 + 0.4 * ppr_avg_last_5 + 0.2 * ppr_avg_season
            WHEN 'WR'::text THEN 0.3 * ppr_avg_last_3 + 0.4 * ppr_avg_last_5 + 0.3 * ppr_avg_season
            WHEN 'TE'::text THEN 0.2 * ppr_avg_last_3 + 0.4 * ppr_avg_last_5 + 0.4 * ppr_avg_season
            ELSE NULL::numeric
        END, 2) AS forecast_ppr_points
   FROM analytics.player_game_features
  WHERE ppr_avg_last_3 IS NOT NULL AND ppr_avg_last_5 IS NOT NULL;;
