# Generated by Django 6.0.1 on 2026-01-12 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Short team code (e.g. SF, DAL)', max_length=5, unique=True)),
                ('name', models.CharField(help_text='Full team name', max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('conference', models.CharField(choices=[('AFC', 'AFC'), ('NFC', 'NFC')], max_length=3)),
                ('division', models.CharField(choices=[('East', 'East'), ('West', 'West'), ('North', 'North'), ('South', 'South')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'ordering': ['conference', 'division', 'name'],
            },
        ),
    ]
