# Generated by Django 6.0.1 on 2026-01-12 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='description',
            field=models.CharField(help_text='Team Description', max_length=400, null=True),
        ),
    ]
